Repository hana-harmoney/frontend, pull requests merged in 2025-09, with the labels that each got.

#69 [fix] 신용도 형식 수정 및 datepicker 수정
  src/app/jobs/[id]/page.tsx
  src/app/profile/[id]/page.tsx
  src/components/ui/datepicker.tsx
Labels: 🔧 fix

#80 [feat] FCM 연동
  package.json
  public/firebase-messaging-sw.js
  public/service-worker.js
  src/app/NotificationProvider.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/firebase/index.ts
  src/lib/api/fcm.ts
  src/lib/fcm.ts
Labels: 🪄 feature

#101 [#98] feat: 수입/지출 내역 합계 추가
  src/app/asset/page.tsx
Labels: 🎨 design

#122 [#121] feat: 금융교육 페이지 이동 연결
  src/app/asset/page.tsx
  src/app/home/page.tsx
  src/assets/images/economic_edu.svg
Labels: 🪄 feature
